name: GnuCash Pocket CI Build

on:
  push: {}
  pull_request:
    branches: [master]
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Prepare Java
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: temurin
      - name: Prepare Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build Application APK
        run: ./gradlew assembleDevelopmentDebug
      - name: Rename Application APK
        run: cp app/build/outputs/apk/development/debug/*.apk application.apk
      - name: Upload Application APK
        uses: actions/upload-artifact@v4
        with:
          name: application-apk
          path: application.apk
          if-no-files-found: error

  unit-test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Prepare Java
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: temurin
      - name: Prepare Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Run Unit Tests
        run: ./gradlew testDevelopmentDebugUnitTest
      - name: Unit Test Summary
        uses: test-summary/action@v2
        if: always()
        with:
          paths: app/build/test-results/testDevelopmentDebugUnitTest/TEST-*.xml
      - name: Upload Unit Test Results for Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: unit-test-results
          path: app/build/test-results/testDevelopmentDebugUnitTest/TEST-*.xml
          if-no-files-found: error

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Prepare Java
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: temurin
      - name: Prepare Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Run Linter
        run: ./gradlew lintDevelopmentDebug

  instrumentation-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Prepare Java
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: temurin
      - name: Prepare Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build Instrumentation APK
        run: ./gradlew assembleDevelopmentDebugAndroidTest
      - name: Rename Instrumentation APK
        run: cp app/build/outputs/apk/androidTest/development/debug/*.apk instrumentation.apk
      - name: Upload Instrumentation APK
        uses: actions/upload-artifact@v4
        with:
          name: instrumentation-apk
          path: instrumentation.apk
          if-no-files-found: error
